version: "3.3"
services:
  react:
    image: node:12.17.0
    working_dir: /code
    volumes:
      - ./ts-my-app:/code
      # - ./my-app:/code
    ports:
      - 3000:3000
    environment: 
      - NODE_ENV=production
    command: yarn start
    container_name: tutorial
    tty: true
    stdin_open: true
